import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'


export default function Home() {

  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Home Page</h2>
        <Link href='/blog' legacyBehavior>Blog Page</Link>
        <br />
        <Link href='/product' legacyBehavior>Product Page</Link>
        <hr />

        <h4>Programetically Routers</h4>

        <button onClick={() => router.push('/product')}>Place Order</button>
        <br />
        <Link href='/users'>Users</Link>
        <br />
        <Link href='/posts'>Posts</Link>

      </main>

    </div>
  )
}
